### ISSUE TITLE
Mirador view not working in Book details page.

### ISSUE THREAD

**Issue by gdkirankumar** [vedavaapi/vedavaapi-mirador#11]
Start the Vedavaapii Web Client Application.
Go to all books page.
select any one of the book for Book details page.
Click on Show Viewer.The Mirador view is blank.

Expected Result:The Mirador View should display with existing pages of a particular book.
Actual result:In book details page Mirador view is blank.

Remarks: Shell Interface Exception is observed in the console.please find the screenshot attached.
 it is working Yesterday.

![shell interface Exception](https://user-images.githubusercontent.com/46882944/55855192-721fad00-5b84-11e9-9fa2-d0ca0dcffbf8.PNG)

**Comment by damooo** [comment]
here: https://github.com/vedavaapi/vedavaapii-web-client/blob/8f35581fed6ca166454574b17ee9d79f4968f02e/src/app/ui/book-information-page/book-information-page.component.ts#L50 we have to pass vv_site_url,

can you add that anna, just like in this
https://github.com/vedavaapi/vedavaapii-web-client/blob/636f98a7496cb181267849b283e258a14d027b5d/src/app/ui/dashboard/dashboard.component.ts#L25
