### ISSUE TITLE
A Shape annotation within a Sequence must not be part of multiple rows.

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi-mirador#6]
Annotators must ensure that a Shape Annotation must be part of only one row and should not overlap into the second row space as it results in Ambiguity for the ordering/content auto-generating algorithm

 This issue has been covered in the below video in a visual manner.

https://www.useloom.com/share/34b2b79f630b4beba939d9c9a74c7aad

**Comment by sai-r-susarla** [comment]
Sequence annotation not in use anymore.
